"""2D sketch solving — DTOs, the ``SketchSolver`` protocol, and backends.

Decision record: RESEARCH §2 (planegcs, LGPL-2.1-or-later, behind the
protocol). Callers import from this package, never from ``planegcs``.
"""

from geometry.sketch.edit import (
    SketchEditError,
    chamfer_sketch,
    extend_sketch,
    fillet_sketch,
    mirror_sketch,
    offset_sketch,
    trim_sketch,
)
from geometry.sketch.expression import (
    SketchExpressionError,
    evaluate_driving_dimensions,
    measure_angle,
    measure_dimension,
    parse_expression,
)
from geometry.sketch.planegcs_solver import PlanegcsSketchSolver
from geometry.sketch.schemas import (
    AngleConstraint,
    CoincidentConstraint,
    ConcentricConstraint,
    DiameterConstraint,
    DimensionConstraint,
    DistanceConstraint,
    EntityPointRef,
    EqualConstraint,
    FixedConstraint,
    HorizontalConstraint,
    MirrorAxis,
    MirrorAxisEntity,
    MirrorAxisPoints,
    ParallelConstraint,
    PerpendicularConstraint,
    Point2D,
    RadiusConstraint,
    SketchArc,
    SketchChamferRequest,
    SketchCircle,
    SketchConstraint,
    SketchCornerResult,
    SketchDefinition,
    SketchEditRequest,
    SketchEditResult,
    SketchEntity,
    SketchFilletRequest,
    SketchLine,
    SketchMirrorRequest,
    SketchMirrorResult,
    SketchOffsetRequest,
    SketchOffsetResult,
    SketchPoint,
    SketchSolveStatus,
    SketchSpline,
    SolvedAngle,
    SolvedDimension,
    SolvedSketch,
    SymmetricConstraint,
    TangentConstraint,
    VerticalConstraint,
)
from geometry.sketch.solver import SketchDefinitionError, SketchSolver

__all__ = [
    "AngleConstraint",
    "CoincidentConstraint",
    "ConcentricConstraint",
    "DiameterConstraint",
    "DimensionConstraint",
    "DistanceConstraint",
    "EntityPointRef",
    "EqualConstraint",
    "FixedConstraint",
    "HorizontalConstraint",
    "MirrorAxis",
    "MirrorAxisEntity",
    "MirrorAxisPoints",
    "ParallelConstraint",
    "PerpendicularConstraint",
    "PlanegcsSketchSolver",
    "Point2D",
    "RadiusConstraint",
    "SketchArc",
    "SketchChamferRequest",
    "SketchCircle",
    "SketchConstraint",
    "SketchCornerResult",
    "SketchDefinition",
    "SketchDefinitionError",
    "SketchEditError",
    "SketchEditRequest",
    "SketchEditResult",
    "SketchEntity",
    "SketchExpressionError",
    "SketchFilletRequest",
    "SketchLine",
    "SketchMirrorRequest",
    "SketchMirrorResult",
    "SketchOffsetRequest",
    "SketchOffsetResult",
    "SketchPoint",
    "SketchSolveStatus",
    "SketchSolver",
    "SketchSpline",
    "SolvedAngle",
    "SolvedDimension",
    "SolvedSketch",
    "SymmetricConstraint",
    "TangentConstraint",
    "VerticalConstraint",
    "chamfer_sketch",
    "evaluate_driving_dimensions",
    "extend_sketch",
    "fillet_sketch",
    "measure_angle",
    "measure_dimension",
    "mirror_sketch",
    "offset_sketch",
    "parse_expression",
    "trim_sketch",
]
