"""Sketch DTOs — thin re-export of the shared py-kit models.

The boundary models live in :mod:`py_kit.schemas.sketch` (single source of
truth, CLAUDE.md DRY rule), migrated there by the "Sketch model + solver API"
item exactly as this module's original docstring promised — sketch feature
params persisted by documents and the solver input/output used here are the
same pydantic shapes. This module stays as the service-local alias, keeping
solver/evaluator/test imports stable (same pattern as :mod:`geometry.schemas`).
"""

from py_kit.schemas.sketch import (
    AngleConstraint,
    CoincidentConstraint,
    ConcentricConstraint,
    DiameterConstraint,
    DimensionConstraint,
    DistanceConstraint,
    EntityId,
    EntityPointRef,
    EqualConstraint,
    FixedConstraint,
    HorizontalConstraint,
    LinearDimensionConstraint,
    MirrorAxis,
    MirrorAxisEntity,
    MirrorAxisPoints,
    ParallelConstraint,
    PerpendicularConstraint,
    Point2D,
    PointName,
    RadiusConstraint,
    SketchArc,
    SketchChamferRequest,
    SketchCircle,
    SketchConstraint,
    SketchCornerResult,
    SketchDefinition,
    SketchEditRequest,
    SketchEditResult,
    SketchEntity,
    SketchEntityBase,
    SketchFilletRequest,
    SketchLine,
    SketchMirrorRequest,
    SketchMirrorResult,
    SketchOffsetRequest,
    SketchOffsetResult,
    SketchPoint,
    SketchSolveStatus,
    SketchSpline,
    SolvedAngle,
    SolvedDimension,
    SolvedSketch,
    SymmetricConstraint,
    TangentConstraint,
    VerticalConstraint,
)

__all__ = [
    "AngleConstraint",
    "CoincidentConstraint",
    "ConcentricConstraint",
    "DiameterConstraint",
    "DimensionConstraint",
    "DistanceConstraint",
    "EntityId",
    "EntityPointRef",
    "EqualConstraint",
    "FixedConstraint",
    "HorizontalConstraint",
    "LinearDimensionConstraint",
    "MirrorAxis",
    "MirrorAxisEntity",
    "MirrorAxisPoints",
    "ParallelConstraint",
    "PerpendicularConstraint",
    "Point2D",
    "PointName",
    "RadiusConstraint",
    "SketchArc",
    "SketchChamferRequest",
    "SketchCircle",
    "SketchConstraint",
    "SketchCornerResult",
    "SketchDefinition",
    "SketchEditRequest",
    "SketchEditResult",
    "SketchEntity",
    "SketchEntityBase",
    "SketchFilletRequest",
    "SketchLine",
    "SketchMirrorRequest",
    "SketchMirrorResult",
    "SketchOffsetRequest",
    "SketchOffsetResult",
    "SketchPoint",
    "SketchSolveStatus",
    "SketchSpline",
    "SolvedAngle",
    "SolvedDimension",
    "SolvedSketch",
    "SymmetricConstraint",
    "TangentConstraint",
    "VerticalConstraint",
]
