"""documents feature tree — write rules, edges, rollback, concurrency.

Runs the SAME application code against SQLite (always) and a real scratch
PostgreSQL with the actual migrations applied (see conftest.py for the
dialect split and what each backend does/doesn't exercise).

The rows asserted in the round-trip test are docs/design/feature-tree.md §6
verbatim (uuids generated by the service, as designed).
"""

import asyncio
import uuid
from collections.abc import Iterator
from typing import Any

import pytest
import sqlalchemy as sa
from documents.db import Feature, FeatureDependency
from documents.main import DocumentsSettings, build_app
from fastapi.testclient import TestClient
from py_kit.db import async_dsn, enable_sqlite_foreign_keys
from py_kit.schemas.features import FEATURE_REGISTRY
from py_kit.schemas.parts import PRINCIPAL_HEADER
from sqlalchemy.exc import DBAPIError
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine

OWNER = "6f3f6b64-0000-4000-8000-00000000000a"
OTHER = "6f3f6b64-0000-4000-8000-00000000000b"

#: docs/design/feature-tree.md §6 — sketch params, verbatim.
SKETCH_PARAMS: dict[str, Any] = {
    "plane": {"kind": "datum_plane", "plane": "XY"},
    "entities": [
        {
            "construction": False,
            "id": "e1",
            "kind": "line",
            "start": {"x": 0.0, "y": 0.0},
            "end": {"x": 40.0, "y": 0.0},
        },
        {
            "construction": False,
            "id": "e2",
            "kind": "line",
            "start": {"x": 40.0, "y": 0.0},
            "end": {"x": 40.0, "y": 25.0},
        },
        {
            "construction": False,
            "id": "e3",
            "kind": "line",
            "start": {"x": 40.0, "y": 25.0},
            "end": {"x": 0.0, "y": 25.0},
        },
        {
            "construction": False,
            "id": "e4",
            "kind": "line",
            "start": {"x": 0.0, "y": 25.0},
            "end": {"x": 0.0, "y": 0.0},
        },
    ],
    "constraints": [
        {
            "kind": "coincident",
            "a": {"entity": "e1", "point": "end"},
            "b": {"entity": "e2", "point": "start"},
        },
        {"kind": "horizontal", "entity": "e1"},
        {"kind": "vertical", "entity": "e2"},
        {
            "kind": "distance",
            "entity": "e1",
            "value_mm": 40.0,
            "expression": None,
            "name": None,
            "driving": None,
        },
        {
            "kind": "distance",
            "entity": "e2",
            "value_mm": 25.0,
            "expression": None,
            "name": None,
            "driving": None,
        },
    ],
}


def _sketch_envelope() -> dict[str, Any]:
    # `suppressed` is the additive envelope flag (py-kit FeatureEnvelopeBase,
    # feature-tree.md §4.3a): a normal field defaulting False, so a round-tripped
    # feature response carries it verbatim — exactly like the `merge` param below.
    return {
        "type": "sketch",
        "version": 1,
        "suppressed": False,
        "params": SKETCH_PARAMS,
    }


def _datum_envelope(offset_mm: float = 30.0, flip: bool = False) -> dict[str, Any]:
    #: An offset datum plane (docs/design/datum-planes.md §3): non-body-affecting.
    return {
        "type": "datum",
        "version": 1,
        "params": {"base": "XY", "offset_mm": offset_mm, "flip": flip},
    }


def _sketch_on_feature_envelope(datum_id: str) -> dict[str, Any]:
    #: A sketch whose plane references a datum feature by id (the widened
    #: FeatureRef acceptance — datum-planes §4).
    params = {**SKETCH_PARAMS, "plane": {"kind": "feature", "feature_id": datum_id}}
    return {"type": "sketch", "version": 1, "params": params}


def _datum_on_face_envelope(target_id: str) -> dict[str, Any]:
    #: An on_face datum (docs/design/datum-planes.md §7) naming a PLANAR face of
    #: an earlier body-affecting feature by a stage-1 SubshapeRef signature
    #: (topological-naming.md §4). The signature values are illustrative — the
    #: documents write path never resolves them, it only materializes the
    #: SubshapeRef.feature_id into feature_dependencies.
    return {
        "type": "datum",
        "version": 1,
        "params": {
            "kind": "on_face",
            "offset_mm": 0.0,
            "face": {
                "kind": "subshape",
                "feature_id": target_id,
                "subshape_type": "face",
                "selector": {
                    "selector_version": 1,
                    "signature": {
                        "normal": {"x": 0.0, "y": 0.0, "z": 1.0},
                        "centroid": {"x": 20.0, "y": 12.5, "z": 10.0},
                        "area_mm2": 1000.0,
                    },
                },
            },
        },
    }


def _shell_envelope(target_id: str) -> dict[str, Any]:
    #: A shell feature whose picked-face selector names a PLANAR face of an
    #: earlier body-affecting feature by a stage-1 SubshapeRef signature — the
    #: SAME face-ref shape the on_face datum uses (topological-naming.md §4). The
    #: documents write path never resolves the signature, it only materializes
    #: the SubshapeRef.feature_id into feature_dependencies (like the on_face
    #: datum), so deleting the referenced body feature is a 409-with-dependents.
    return {
        "type": "shell",
        "version": 1,
        "params": {
            "thickness_mm": 2.0,
            "faces": {
                "kind": "faces",
                "refs": [
                    {
                        "kind": "subshape",
                        "feature_id": target_id,
                        "subshape_type": "face",
                        "selector": {
                            "selector_version": 1,
                            "signature": {
                                "normal": {"x": 0.0, "y": 0.0, "z": 1.0},
                                "centroid": {"x": 20.0, "y": 12.5, "z": 10.0},
                                "area_mm2": 1000.0,
                            },
                        },
                    }
                ],
            },
        },
    }


def _draft_envelope(target_id: str) -> dict[str, Any]:
    #: A draft feature whose picked-face selector names a PLANAR face of an
    #: earlier body-affecting feature by a stage-1 SubshapeRef signature — the
    #: SAME face-ref shape shell / the on_face datum use (topological-naming.md
    #: §4). The documents write path never resolves the signature, it only
    #: materializes the SubshapeRef.feature_id into feature_dependencies (like the
    #: shell opening), so deleting the referenced body feature is a
    #: 409-with-dependents. The neutral plane is a principal datum (no ref).
    return {
        "type": "draft",
        "version": 1,
        "params": {
            "angle_deg": 5.0,
            "neutral_plane": {"kind": "datum", "base": "XY"},
            "faces": {
                "kind": "faces",
                "refs": [
                    {
                        "kind": "subshape",
                        "feature_id": target_id,
                        "subshape_type": "face",
                        "selector": {
                            "selector_version": 1,
                            "signature": {
                                "normal": {"x": 1.0, "y": 0.0, "z": 0.0},
                                "centroid": {"x": 40.0, "y": 20.0, "z": 10.0},
                                "area_mm2": 800.0,
                            },
                        },
                    }
                ],
            },
        },
    }


def _extrude_envelope(sketch_id: str) -> dict[str, Any]:
    #: §6 — extrude params, verbatim (profile id substituted).
    return {
        "type": "extrude",
        "version": 1,
        # Additive envelope suppress flag (feature-tree.md §4.3a), defaults False.
        "suppressed": False,
        "params": {
            "profile": {"kind": "feature", "feature_id": sketch_id},
            "distance_mm": 10.0,
            "operation": "add",
            "direction": "normal",
            # Additive multi-body "Merge result" flag (design multi-body.md §MB-0),
            # defaults True — a round-tripped envelope carries it verbatim.
            "merge": True,
        },
    }


#: A minimal STEP part-21 payload for an import base feature
#: (docs/design/step-import.md §2b — inline STEP text). Documents never parses
#: the geometry; it stores `data` verbatim as the feature's params.
STEP_TEXT = "ISO-10303-21;\nHEADER;\nENDSEC;\nDATA;\nENDSEC;\nEND-ISO-10303-21;\n"


def _import_envelope(data: str = STEP_TEXT) -> dict[str, Any]:
    #: An import base feature (docs/design/step-import.md §1): body-affecting,
    #: produces the base body from its inline STEP text, no picked geometry / no
    #: FeatureRef (materializes no dependency edge).
    return {
        "type": "import",
        "version": 1,
        # Additive envelope suppress flag (feature-tree.md §4.3a), defaults False.
        "suppressed": False,
        "params": {"kind": "inline", "format": "step", "data": data},
    }


@pytest.fixture
def client(any_db_url: str) -> Iterator[TestClient]:
    settings = DocumentsSettings(postgres_url=any_db_url)
    with TestClient(build_app(settings)) as test_client:
        yield test_client


def _headers(owner: str = OWNER) -> dict[str, str]:
    return {PRINCIPAL_HEADER: owner}


def _envelope_error(body: dict[str, Any]) -> dict[str, Any]:
    assert set(body) == {"error"}
    error: dict[str, Any] = body["error"]
    assert set(error) == {"code", "message", "details", "request_id"}
    return error


def _create_part(
    client: TestClient, name: str = "demo-block", owner: str = OWNER
) -> str:
    response = client.post(
        "/api/v1/parts", json={"name": name}, headers=_headers(owner)
    )
    assert response.status_code == 201, response.text
    part_id: str = response.json()["id"]
    return part_id


def _create_feature(
    client: TestClient,
    part_id: str,
    name: str,
    feature: dict[str, Any],
    expected_tree_version: int,
    owner: str = OWNER,
) -> dict[str, Any]:
    response = client.post(
        f"/api/v1/parts/{part_id}/features",
        json={
            "name": name,
            "feature": feature,
            "expected_tree_version": expected_tree_version,
        },
        headers=_headers(owner),
    )
    assert response.status_code == 201, response.text
    body: dict[str, Any] = response.json()
    return body


def _tree(client: TestClient, part_id: str, owner: str = OWNER) -> dict[str, Any]:
    response = client.get(f"/api/v1/parts/{part_id}/features", headers=_headers(owner))
    assert response.status_code == 200, response.text
    body: dict[str, Any] = response.json()
    return body


def _sketch_and_extrude(client: TestClient, part_id: str) -> tuple[str, str]:
    """§6 worked example: Sketch1 at 0, Extrude1 at 1. Returns their ids."""
    sketch = _create_feature(client, part_id, "Sketch1", _sketch_envelope(), 0)
    sketch_id: str = sketch["feature"]["id"]
    extrude = _create_feature(
        client, part_id, "Extrude1", _extrude_envelope(sketch_id), 1
    )
    extrude_id: str = extrude["feature"]["id"]
    return sketch_id, extrude_id


def direct_engine(url: str) -> AsyncEngine:
    """A direct-inspection engine with SQLite FK enforcement matching the app."""
    engine = create_async_engine(async_dsn(url))
    enable_sqlite_foreign_keys(engine)
    return engine


async def _fetch_all(url: str, statement: sa.Select[Any]) -> list[sa.Row[Any]]:
    engine = direct_engine(url)
    try:
        async with engine.connect() as connection:
            return list((await connection.execute(statement)).all())
    finally:
        await engine.dispose()


# --- §6 worked example round-trip -------------------------------------------------


def test_worked_example_rows_round_trip(client: TestClient, any_db_url: str) -> None:
    part_id = _create_part(client)
    sketch_id, extrude_id = _sketch_and_extrude(client, part_id)

    tree = _tree(client, part_id)
    assert tree["part_id"] == part_id
    assert tree["tree_version"] == 2  # two mutations
    assert tree["rollback_feature_id"] is None

    sketch, extrude = tree["features"]
    # Row 1 — the sketch, §6 verbatim.
    assert (sketch["order_index"], sketch["name"]) == (0, "Sketch1")
    assert sketch["feature"] == _sketch_envelope()
    assert sketch["rolled_back"] is False
    # Row 2 — the extrude, referencing the sketch BY FEATURE ID.
    assert (extrude["order_index"], extrude["name"]) == (1, "Extrude1")
    assert extrude["feature"] == _extrude_envelope(sketch_id)
    assert extrude["rolled_back"] is False

    # Stored split (§1.3): type/param_version promoted to columns, params
    # holding only the payload — asserted against the DB, not the DTO.
    rows = asyncio.run(
        _fetch_all(
            any_db_url,
            sa.select(Feature.type, Feature.param_version, Feature.params).order_by(
                Feature.order_index
            ),
        )
    )
    assert [(row[0], row[1]) for row in rows] == [("sketch", 1), ("extrude", 1)]
    assert rows[0][2] == SKETCH_PARAMS
    assert rows[1][2] == _extrude_envelope(sketch_id)["params"]

    # §6 — the derived feature_dependencies row.
    edges = asyncio.run(
        _fetch_all(
            any_db_url,
            sa.select(
                FeatureDependency.part_id,
                FeatureDependency.feature_id,
                FeatureDependency.references_feature_id,
            ),
        )
    )
    assert [(str(e[0]), str(e[1]), str(e[2])) for e in edges] == [
        (part_id, extrude_id, sketch_id)
    ]


# --- optimistic concurrency (§1.2: stale → 422, distinct from the 409) --------------


def test_stale_tree_version_is_422(client: TestClient) -> None:
    part_id = _create_part(client)
    _create_feature(client, part_id, "Sketch1", _sketch_envelope(), 0)

    # Replaying the same expected version is stale — the tree moved to 1.
    response = client.post(
        f"/api/v1/parts/{part_id}/features",
        json={
            "name": "Sketch2",
            "feature": _sketch_envelope(),
            "expected_tree_version": 0,
        },
        headers=_headers(),
    )
    assert response.status_code == 422
    error = _envelope_error(response.json())
    assert error["code"] == "stale_tree_version"
    assert error["details"] == {"provided": 0, "current": 1}


def test_stale_version_rejected_on_every_mutation_route(client: TestClient) -> None:
    part_id = _create_part(client)
    sketch_id, extrude_id = _sketch_and_extrude(client, part_id)
    stale = 1  # current is 2

    requests = [
        client.patch(
            f"/api/v1/parts/{part_id}/features/{sketch_id}",
            json={"expected_tree_version": stale, "name": "Renamed"},
            headers=_headers(),
        ),
        client.delete(
            f"/api/v1/parts/{part_id}/features/{extrude_id}",
            params={"expected_tree_version": stale},
            headers=_headers(),
        ),
        client.put(
            f"/api/v1/parts/{part_id}/features/order",
            json={"expected_tree_version": stale, "order": [sketch_id, extrude_id]},
            headers=_headers(),
        ),
        client.put(
            f"/api/v1/parts/{part_id}/rollback",
            json={"expected_tree_version": stale, "rollback_feature_id": None},
            headers=_headers(),
        ),
    ]
    for response in requests:
        assert response.status_code == 422, response.text
        assert _envelope_error(response.json())["code"] == "stale_tree_version"


def test_any_mutation_bumps_tree_version_including_rename(client: TestClient) -> None:
    part_id = _create_part(client)
    sketch_id, _ = _sketch_and_extrude(client, part_id)
    response = client.patch(
        f"/api/v1/parts/{part_id}/features/{sketch_id}",
        json={"expected_tree_version": 2, "name": "Base sketch"},
        headers=_headers(),
    )
    assert response.status_code == 200
    assert response.json()["tree_version"] == 3
    assert response.json()["feature"]["name"] == "Base sketch"


# --- §4.3a feature suppress -----------------------------------------------------------


def test_create_with_suppressed_persists(client: TestClient, any_db_url: str) -> None:
    """A feature CAN be born suppressed (slice-1 review: create must NOT drop
    `suppressed: true`). It round-trips true in the response AND the DB column."""
    part_id = _create_part(client)
    envelope = {**_sketch_envelope(), "suppressed": True}
    body = _create_feature(client, part_id, "Sketch1", envelope, 0)
    assert body["feature"]["feature"]["suppressed"] is True

    tree = _tree(client, part_id)
    assert tree["features"][0]["feature"]["suppressed"] is True

    rows = asyncio.run(_fetch_all(any_db_url, sa.select(Feature.suppressed)))
    assert [row[0] for row in rows] == [True]


def test_suppress_toggle_flips_flag_bumps_version_and_restores(
    client: TestClient,
) -> None:
    """The dedicated toggle flips only `suppressed`, bumps tree_version, and is
    reversible — un-suppress restores the feature."""
    part_id = _create_part(client)
    sketch_id, _ = _sketch_and_extrude(client, part_id)  # tree_version == 2

    suppressed = client.patch(
        f"/api/v1/parts/{part_id}/features/{sketch_id}/suppress",
        json={"expected_tree_version": 2, "suppressed": True},
        headers=_headers(),
    )
    assert suppressed.status_code == 200, suppressed.text
    assert suppressed.json()["tree_version"] == 3
    assert suppressed.json()["feature"]["feature"]["suppressed"] is True
    # Params are untouched by the toggle (no re-validation / edge rewrite).
    assert suppressed.json()["feature"]["feature"]["params"] == SKETCH_PARAMS

    restored = client.patch(
        f"/api/v1/parts/{part_id}/features/{sketch_id}/suppress",
        json={"expected_tree_version": 3, "suppressed": False},
        headers=_headers(),
    )
    assert restored.status_code == 200, restored.text
    assert restored.json()["tree_version"] == 4
    assert restored.json()["feature"]["feature"]["suppressed"] is False


def test_suppress_toggle_stale_version_is_422_no_change(client: TestClient) -> None:
    """A stale expected_tree_version is rejected 422 and leaves the flag intact."""
    part_id = _create_part(client)
    sketch_id, _ = _sketch_and_extrude(client, part_id)  # tree_version == 2

    response = client.patch(
        f"/api/v1/parts/{part_id}/features/{sketch_id}/suppress",
        json={"expected_tree_version": 1, "suppressed": True},  # stale
        headers=_headers(),
    )
    assert response.status_code == 422
    assert _envelope_error(response.json())["code"] == "stale_tree_version"

    tree = _tree(client, part_id)
    assert tree["tree_version"] == 2
    assert tree["features"][0]["feature"]["suppressed"] is False


def test_suppress_toggle_undoable(client: TestClient) -> None:
    """The suppress toggle records history, so undo restores the prior flag."""
    part_id = _create_part(client)
    sketch_id, _ = _sketch_and_extrude(client, part_id)  # tree_version == 2

    client.patch(
        f"/api/v1/parts/{part_id}/features/{sketch_id}/suppress",
        json={"expected_tree_version": 2, "suppressed": True},
        headers=_headers(),
    )
    undo = client.post(
        f"/api/v1/parts/{part_id}/undo",
        json={"expected_tree_version": 3},
        headers=_headers(),
    )
    assert undo.status_code == 200, undo.text
    assert undo.json()["features"][0]["feature"]["suppressed"] is False


def test_suppress_toggle_owner_scoped_and_404(client: TestClient) -> None:
    part_id = _create_part(client)
    sketch_id, _ = _sketch_and_extrude(client, part_id)
    foreign = client.patch(
        f"/api/v1/parts/{part_id}/features/{sketch_id}/suppress",
        json={"expected_tree_version": 2, "suppressed": True},
        headers=_headers(OTHER),
    )
    assert foreign.status_code == 404
    unknown = client.patch(
        f"/api/v1/parts/{part_id}/features/{uuid.uuid4()}/suppress",
        json={"expected_tree_version": 2, "suppressed": True},
        headers=_headers(),
    )
    assert unknown.status_code == 404


# --- §2.2 reference rules ------------------------------------------------------------


def test_reference_to_unknown_feature_rejected(client: TestClient) -> None:
    part_id = _create_part(client)
    response = client.post(
        f"/api/v1/parts/{part_id}/features",
        json={
            "name": "Extrude1",
            "feature": _extrude_envelope(str(uuid.uuid4())),
            "expected_tree_version": 0,
        },
        headers=_headers(),
    )
    assert response.status_code == 422
    assert _envelope_error(response.json())["code"] == "reference_not_found"


def test_cross_part_reference_rejected(client: TestClient) -> None:
    part_a = _create_part(client, name="part-a")
    sketch = _create_feature(client, part_a, "Sketch1", _sketch_envelope(), 0)
    part_b = _create_part(client, name="part-b")

    response = client.post(
        f"/api/v1/parts/{part_b}/features",
        json={
            "name": "Extrude1",
            "feature": _extrude_envelope(sketch["feature"]["id"]),
            "expected_tree_version": 0,
        },
        headers=_headers(),
    )
    assert response.status_code == 422
    assert _envelope_error(response.json())["code"] == "reference_not_found"


def test_forward_reference_rejected_on_rolled_back_insert(client: TestClient) -> None:
    """Insert-after-the-bar must not see features BELOW the bar as targets:
    a reference to a feature after the insertion point is strictly forward."""
    part_id = _create_part(client)
    sketch_id, _extrude = _sketch_and_extrude(client, part_id)
    # Bar to the sketch (index 0): inserts now land at index 1.
    response = client.put(
        f"/api/v1/parts/{part_id}/rollback",
        json={"expected_tree_version": 2, "rollback_feature_id": sketch_id},
        headers=_headers(),
    )
    assert response.status_code == 200

    # A second sketch lands at index 1 and moves the bar; referencing IT from
    # a later insert is fine — but referencing the ORIGINAL extrude (now at
    # index 2) from a new insert at index 2 is forward → rejected.
    second = _create_feature(client, part_id, "Sketch2", _sketch_envelope(), 3)
    assert second["feature"]["order_index"] == 1

    tree = _tree(client, part_id)
    original_extrude = tree["features"][2]
    assert original_extrude["name"] == "Extrude1"
    response = client.post(
        f"/api/v1/parts/{part_id}/features",
        json={
            "name": "Extrude2",
            # Would extrude a "sketch"… except the target is the original
            # EXTRUDE at index 2 — forward of the insertion point (index 2).
            "feature": _extrude_envelope(original_extrude["id"]),
            "expected_tree_version": 4,
        },
        headers=_headers(),
    )
    assert response.status_code == 422
    assert _envelope_error(response.json())["code"] == "reference_not_earlier"


def test_reorder_violating_backward_only_refs_rejected(client: TestClient) -> None:
    part_id = _create_part(client)
    sketch_id, extrude_id = _sketch_and_extrude(client, part_id)
    response = client.put(
        f"/api/v1/parts/{part_id}/features/order",
        json={"expected_tree_version": 2, "order": [extrude_id, sketch_id]},
        headers=_headers(),
    )
    assert response.status_code == 422
    error = _envelope_error(response.json())
    assert error["code"] == "reference_not_earlier"
    assert error["details"] == {
        "feature_id": extrude_id,
        "references_feature_id": sketch_id,
    }
    # Nothing moved, nothing bumped.
    tree = _tree(client, part_id)
    assert tree["tree_version"] == 2
    assert [f["name"] for f in tree["features"]] == ["Sketch1", "Extrude1"]


def test_type_incompatible_reference_rejected(client: TestClient) -> None:
    part_id = _create_part(client)
    _sketch_id, extrude_id = _sketch_and_extrude(client, part_id)
    response = client.post(
        f"/api/v1/parts/{part_id}/features",
        json={
            "name": "Extrude2",
            "feature": _extrude_envelope(extrude_id),  # extrude-of-extrude
            "expected_tree_version": 2,
        },
        headers=_headers(),
    )
    assert response.status_code == 422
    error = _envelope_error(response.json())
    assert error["code"] == "reference_type_invalid"
    assert error["details"]["actual_type"] == "extrude"
    assert error["details"]["allowed_types"] == ["sketch"]


def test_sketch_on_datum_plane_accepted_and_edge_materialized(
    client: TestClient, any_db_url: str
) -> None:
    """The datum-planes unlock at the write layer (§4): a datum feature first,
    then a sketch whose plane FeatureRef points at it — now ACCEPTED (the slot's
    allowed_types widened to {'datum'}) and materialized as a sketch->datum
    dependency edge, so deleting the datum becomes a 409-with-dependents."""
    part_id = _create_part(client)
    datum = _create_feature(client, part_id, "Plane1", _datum_envelope(), 0)
    datum_id: str = datum["feature"]["id"]
    sketch = _create_feature(
        client, part_id, "Sketch1", _sketch_on_feature_envelope(datum_id), 1
    )
    sketch_id: str = sketch["feature"]["id"]

    edges = asyncio.run(
        _fetch_all(
            any_db_url,
            sa.select(
                FeatureDependency.feature_id,
                FeatureDependency.references_feature_id,
            ),
        )
    )
    assert [(str(e[0]), str(e[1])) for e in edges] == [(sketch_id, datum_id)]

    # The materialized edge protects the datum from a lone delete (§2.3).
    response = client.delete(
        f"/api/v1/parts/{part_id}/features/{datum_id}?expected_tree_version=2",
        headers=_headers(),
    )
    assert response.status_code == 409
    assert _envelope_error(response.json())["code"] == "feature_has_dependents"


def test_sketch_before_its_datum_rejected_not_earlier(client: TestClient) -> None:
    """Strict-backward still holds for the new edge (§5): a sketch cannot
    reference a datum that comes later. Here the sketch is created first, so a
    forward FeatureRef to a not-yet-existing datum is reference_not_found; the
    ordering guarantee that a datum evaluates before its sketch is what the
    geometry eval-time backstop relies on."""
    part_id = _create_part(client)
    # Reference an id that does not (yet) exist earlier in the tree.
    phantom_datum = str(uuid.uuid4())
    response = client.post(
        f"/api/v1/parts/{part_id}/features",
        json={
            "name": "Sketch1",
            "feature": _sketch_on_feature_envelope(phantom_datum),
            "expected_tree_version": 0,
        },
        headers=_headers(),
    )
    assert response.status_code == 422
    assert _envelope_error(response.json())["code"] == "reference_not_found"


def test_reorder_sketch_before_datum_rejected(client: TestClient) -> None:
    """A reorder that moves a sketch before the datum it sits on is rejected by
    the strict-backward re-check on the materialized sketch->datum edge (§5)."""
    part_id = _create_part(client)
    datum = _create_feature(client, part_id, "Plane1", _datum_envelope(), 0)
    datum_id: str = datum["feature"]["id"]
    sketch = _create_feature(
        client, part_id, "Sketch1", _sketch_on_feature_envelope(datum_id), 1
    )
    sketch_id: str = sketch["feature"]["id"]

    response = client.put(
        f"/api/v1/parts/{part_id}/features/order",
        json={"expected_tree_version": 2, "order": [sketch_id, datum_id]},
        headers=_headers(),
    )
    assert response.status_code == 422
    error = _envelope_error(response.json())
    assert error["code"] == "reference_not_earlier"
    assert error["details"] == {
        "feature_id": sketch_id,
        "references_feature_id": datum_id,
    }
    assert sketch_id  # (fixture part is intact)


def test_on_face_datum_blocks_deletion_of_referenced_body_feature(
    client: TestClient, any_db_url: str
) -> None:
    """Review 🟡 (sketch-on-face): an on_face datum's face SubshapeRef names a
    PLANAR face of a body-affecting feature (topo-naming §4). Its feature_id
    materializes into feature_dependencies EXACTLY like a FeatureRef, so deleting
    the referenced extrude is a write-time 409-with-dependents (§2.3) — the named
    face reference is protected identically to a whole-feature reference."""
    part_id = _create_part(client)
    sketch_id, extrude_id = _sketch_and_extrude(client, part_id)  # orders 0, 1
    datum = _create_feature(
        client, part_id, "Plane1", _datum_on_face_envelope(extrude_id), 2
    )
    datum_id: str = datum["feature"]["id"]

    edges = asyncio.run(
        _fetch_all(
            any_db_url,
            sa.select(
                FeatureDependency.feature_id,
                FeatureDependency.references_feature_id,
            ),
        )
    )
    # sketch->? Extrude1->Sketch1 and Plane1->Extrude1 are the two edges.
    assert (datum_id, extrude_id) in [(str(e[0]), str(e[1])) for e in edges]

    response = client.delete(
        f"/api/v1/parts/{part_id}/features/{extrude_id}?expected_tree_version=3",
        headers=_headers(),
    )
    assert response.status_code == 409
    error = _envelope_error(response.json())
    assert error["code"] == "feature_has_dependents"
    assert {d["id"] for d in error["details"]["dependents"]} == {datum_id}
    assert sketch_id  # fixture intact


def test_shell_face_ref_blocks_deletion_of_referenced_body_feature(
    client: TestClient, any_db_url: str
) -> None:
    """A shell's picked-face SubshapeRef names a PLANAR face of a body-affecting
    feature (topo-naming §4) — the SAME face-ref shape sketch-on-face uses. Its
    feature_id materializes into feature_dependencies EXACTLY like a FeatureRef,
    so deleting the referenced extrude is a write-time 409-with-dependents
    (§2.3): the picked opening is protected identically to a whole-feature
    reference. (A shell with an EMPTY faces list carries no ref — no edge — so
    this protection applies only to opened faces.)"""
    part_id = _create_part(client)
    sketch_id, extrude_id = _sketch_and_extrude(client, part_id)  # orders 0, 1
    shell = _create_feature(client, part_id, "Shell1", _shell_envelope(extrude_id), 2)
    shell_id: str = shell["feature"]["id"]

    edges = asyncio.run(
        _fetch_all(
            any_db_url,
            sa.select(
                FeatureDependency.feature_id,
                FeatureDependency.references_feature_id,
            ),
        )
    )
    # Shell1->Extrude1 is a dependency edge (alongside Extrude1->Sketch1).
    assert (shell_id, extrude_id) in [(str(e[0]), str(e[1])) for e in edges]

    response = client.delete(
        f"/api/v1/parts/{part_id}/features/{extrude_id}?expected_tree_version=3",
        headers=_headers(),
    )
    assert response.status_code == 409
    error = _envelope_error(response.json())
    assert error["code"] == "feature_has_dependents"
    assert {d["id"] for d in error["details"]["dependents"]} == {shell_id}
    assert sketch_id  # fixture intact


def test_draft_face_ref_blocks_deletion_of_referenced_body_feature(
    client: TestClient, any_db_url: str
) -> None:
    """A draft's picked-face SubshapeRef names a PLANAR face of a body-affecting
    feature (topo-naming §4) — the SAME face-ref shape shell / sketch-on-face use.
    Its feature_id materializes into feature_dependencies EXACTLY like a
    FeatureRef, so deleting the referenced extrude is a write-time
    409-with-dependents (§2.3): the tapered face is protected identically to a
    whole-feature reference."""
    part_id = _create_part(client)
    sketch_id, extrude_id = _sketch_and_extrude(client, part_id)  # orders 0, 1
    draft = _create_feature(client, part_id, "Draft1", _draft_envelope(extrude_id), 2)
    draft_id: str = draft["feature"]["id"]

    edges = asyncio.run(
        _fetch_all(
            any_db_url,
            sa.select(
                FeatureDependency.feature_id,
                FeatureDependency.references_feature_id,
            ),
        )
    )
    # Draft1->Extrude1 is a dependency edge (alongside Extrude1->Sketch1).
    assert (draft_id, extrude_id) in [(str(e[0]), str(e[1])) for e in edges]

    response = client.delete(
        f"/api/v1/parts/{part_id}/features/{extrude_id}?expected_tree_version=3",
        headers=_headers(),
    )
    assert response.status_code == 409
    error = _envelope_error(response.json())
    assert error["code"] == "feature_has_dependents"
    assert {d["id"] for d in error["details"]["dependents"]} == {draft_id}
    assert sketch_id  # fixture intact


def test_on_face_datum_rejects_non_body_affecting_target(client: TestClient) -> None:
    """Review 🟡 (sketch-on-face): the on_face face slot accepts only
    BODY_AFFECTING_FEATURE_TYPES (topo-naming §4 — a face is named on a body).
    Pointing it at the SKETCH (not body-affecting) is a write-time
    reference_type_invalid 422, never a datum that resolves against a
    face-less feature."""
    part_id = _create_part(client)
    sketch_id, _extrude_id = _sketch_and_extrude(client, part_id)  # orders 0, 1
    response = client.post(
        f"/api/v1/parts/{part_id}/features",
        json={
            "name": "Plane1",
            "feature": _datum_on_face_envelope(sketch_id),  # sketch is not a body
            "expected_tree_version": 2,
        },
        headers=_headers(),
    )
    assert response.status_code == 422
    error = _envelope_error(response.json())
    assert error["code"] == "reference_type_invalid"
    assert error["details"]["actual_type"] == "sketch"
    assert error["details"]["slot"] == "face"


# --- §2.3 delete pre-check + deferred backstop ---------------------------------------


def test_delete_with_dependents_409_lists_them(client: TestClient) -> None:
    part_id = _create_part(client)
    sketch_id, extrude_id = _sketch_and_extrude(client, part_id)

    response = client.delete(
        f"/api/v1/parts/{part_id}/features/{sketch_id}",
        params={"expected_tree_version": 2},
        headers=_headers(),
    )
    assert response.status_code == 409
    error = _envelope_error(response.json())
    assert error["code"] == "feature_has_dependents"
    assert error["details"] == {"dependents": [{"id": extrude_id, "name": "Extrude1"}]}
    # Conflict is not a mutation: nothing deleted, version unchanged.
    tree = _tree(client, part_id)
    assert tree["tree_version"] == 2
    assert len(tree["features"]) == 2


def test_delete_dependent_then_target_succeeds_and_renumbers(
    client: TestClient,
) -> None:
    part_id = _create_part(client)
    sketch_id, extrude_id = _sketch_and_extrude(client, part_id)

    response = client.delete(
        f"/api/v1/parts/{part_id}/features/{extrude_id}",
        params={"expected_tree_version": 2},
        headers=_headers(),
    )
    assert response.status_code == 200, response.text
    assert response.json()["tree_version"] == 3

    response = client.delete(
        f"/api/v1/parts/{part_id}/features/{sketch_id}",
        params={"expected_tree_version": 3},
        headers=_headers(),
    )
    assert response.status_code == 200
    assert response.json()["features"] == []


def test_delete_middle_feature_renumbers_suffix(client: TestClient) -> None:
    part_id = _create_part(client)
    first = _create_feature(client, part_id, "Sketch1", _sketch_envelope(), 0)
    second = _create_feature(client, part_id, "Sketch2", _sketch_envelope(), 1)
    third = _create_feature(client, part_id, "Sketch3", _sketch_envelope(), 2)

    response = client.delete(
        f"/api/v1/parts/{part_id}/features/{second['feature']['id']}",
        params={"expected_tree_version": 3},
        headers=_headers(),
    )
    assert response.status_code == 200
    tree = response.json()
    assert [(f["name"], f["order_index"]) for f in tree["features"]] == [
        ("Sketch1", 0),
        ("Sketch3", 1),
    ]
    assert {first["feature"]["id"], third["feature"]["id"]} == {
        f["id"] for f in tree["features"]
    }


def test_whole_part_delete_succeeds_with_referenced_features(
    client: TestClient, any_db_url: str
) -> None:
    """The review-log 🔴 fix: a part whose tree contains a reference must be
    deletable — the parts→features CASCADE plus the DEFERRED target-side FK
    make the whole-part delete legal at commit time (design §2.3). RESTRICT
    (or an immediate check) would abort on the sketch's RI trigger while the
    extrude's edge still exists."""
    part_id = _create_part(client)
    _sketch_and_extrude(client, part_id)

    response = client.delete(f"/api/v1/parts/{part_id}", headers=_headers())
    assert response.status_code == 204, response.text

    features = asyncio.run(
        _fetch_all(
            any_db_url,
            sa.select(Feature.id).where(Feature.part_id == uuid.UUID(part_id)),
        )
    )
    edges = asyncio.run(_fetch_all(any_db_url, sa.select(FeatureDependency.feature_id)))
    assert features == []
    assert edges == []


def test_lone_delete_of_referenced_feature_fails_at_commit(
    client: TestClient, any_db_url: str
) -> None:
    """The DB backstop behind the friendly 409: a delete that slips past the
    pre-check (simulated here with a direct row delete) still fails when the
    DEFERRED target-side FK is checked at COMMIT — a code-path bug can never
    silently corrupt the tree (design §2.3)."""
    part_id = _create_part(client)
    sketch_id, _extrude_id = _sketch_and_extrude(client, part_id)

    async def rogue_delete() -> None:
        engine = direct_engine(any_db_url)
        try:
            async with engine.begin() as connection:
                await connection.execute(
                    sa.delete(Feature).where(Feature.id == uuid.UUID(sketch_id))
                )
                # begin() commits on exit → the deferred FK fires HERE.
        finally:
            await engine.dispose()

    with pytest.raises(DBAPIError):
        asyncio.run(rogue_delete())

    # The tree survived intact.
    tree = _tree(client, part_id)
    assert [f["name"] for f in tree["features"]] == ["Sketch1", "Extrude1"]


# --- reorder + rollback (§1.2, §3) ----------------------------------------------------


def test_reorder_applies_permutation_and_bar_survives(client: TestClient) -> None:
    part_id = _create_part(client)
    first = _create_feature(client, part_id, "SketchA", _sketch_envelope(), 0)
    second = _create_feature(client, part_id, "SketchB", _sketch_envelope(), 1)
    a_id: str = first["feature"]["id"]
    b_id: str = second["feature"]["id"]

    # Bar onto SketchA — SketchB is rolled back.
    response = client.put(
        f"/api/v1/parts/{part_id}/rollback",
        json={"expected_tree_version": 2, "rollback_feature_id": a_id},
        headers=_headers(),
    )
    assert response.status_code == 200

    response = client.put(
        f"/api/v1/parts/{part_id}/features/order",
        json={"expected_tree_version": 3, "order": [b_id, a_id]},
        headers=_headers(),
    )
    assert response.status_code == 200, response.text
    tree = response.json()
    assert [(f["id"], f["order_index"]) for f in tree["features"]] == [
        (b_id, 0),
        (a_id, 1),
    ]
    # The bar is a feature ID, not an index — it survives renumbering (§3)
    # and the rolled_back flags follow the NEW order.
    assert tree["rollback_feature_id"] == a_id
    assert [f["rolled_back"] for f in tree["features"]] == [False, False]


def test_reorder_must_be_a_full_permutation(client: TestClient) -> None:
    part_id = _create_part(client)
    first = _create_feature(client, part_id, "SketchA", _sketch_envelope(), 0)
    _create_feature(client, part_id, "SketchB", _sketch_envelope(), 1)
    for order in ([], [first["feature"]["id"]], [first["feature"]["id"]] * 2):
        response = client.put(
            f"/api/v1/parts/{part_id}/features/order",
            json={"expected_tree_version": 2, "order": order},
            headers=_headers(),
        )
        assert response.status_code == 422
        assert _envelope_error(response.json())["code"] == "order_not_permutation"


def test_rollback_marks_features_and_insert_lands_after_bar(
    client: TestClient,
) -> None:
    part_id = _create_part(client)
    sketch_id, extrude_id = _sketch_and_extrude(client, part_id)

    response = client.put(
        f"/api/v1/parts/{part_id}/rollback",
        json={"expected_tree_version": 2, "rollback_feature_id": sketch_id},
        headers=_headers(),
    )
    assert response.status_code == 200
    tree = response.json()
    assert tree["rollback_feature_id"] == sketch_id
    assert [f["rolled_back"] for f in tree["features"]] == [False, True]

    # Insert while rolled back: lands immediately after the bar and the bar
    # moves to the new feature (§3).
    created = _create_feature(client, part_id, "Sketch2", _sketch_envelope(), 3)
    assert created["feature"]["order_index"] == 1
    assert created["feature"]["rolled_back"] is False

    tree = _tree(client, part_id)
    assert tree["rollback_feature_id"] == created["feature"]["id"]
    assert [(f["name"], f["rolled_back"]) for f in tree["features"]] == [
        ("Sketch1", False),
        ("Sketch2", False),
        ("Extrude1", True),
    ]
    assert extrude_id == tree["features"][2]["id"]


def test_deleting_bar_feature_resets_bar_to_tip(client: TestClient) -> None:
    part_id = _create_part(client)
    first = _create_feature(client, part_id, "SketchA", _sketch_envelope(), 0)
    second = _create_feature(client, part_id, "SketchB", _sketch_envelope(), 1)
    b_id: str = second["feature"]["id"]

    response = client.put(
        f"/api/v1/parts/{part_id}/rollback",
        json={"expected_tree_version": 2, "rollback_feature_id": b_id},
        headers=_headers(),
    )
    assert response.status_code == 200

    response = client.delete(
        f"/api/v1/parts/{part_id}/features/{b_id}",
        params={"expected_tree_version": 3},
        headers=_headers(),
    )
    assert response.status_code == 200
    tree = response.json()
    assert tree["rollback_feature_id"] is None  # bar back at the tip (§3)
    assert [f["id"] for f in tree["features"]] == [first["feature"]["id"]]


def test_rollback_to_foreign_or_unknown_feature_rejected(client: TestClient) -> None:
    part_id = _create_part(client)
    other_part = _create_part(client, name="other")
    foreign = _create_feature(client, other_part, "Sketch1", _sketch_envelope(), 0)
    for bogus in (str(uuid.uuid4()), foreign["feature"]["id"]):
        response = client.put(
            f"/api/v1/parts/{part_id}/rollback",
            json={"expected_tree_version": 0, "rollback_feature_id": bogus},
            headers=_headers(),
        )
        assert response.status_code == 422
        assert _envelope_error(response.json())["code"] == "reference_not_found"


# --- update (params + edges), type immutability ---------------------------------------


def test_update_params_rewrites_dependency_edges(client: TestClient) -> None:
    part_id = _create_part(client)
    sketch1 = _create_feature(client, part_id, "Sketch1", _sketch_envelope(), 0)
    sketch2 = _create_feature(client, part_id, "Sketch2", _sketch_envelope(), 1)
    s1: str = sketch1["feature"]["id"]
    s2: str = sketch2["feature"]["id"]
    extrude = _create_feature(client, part_id, "Extrude1", _extrude_envelope(s1), 2)
    e_id: str = extrude["feature"]["id"]

    # Re-point the extrude from Sketch1 to Sketch2.
    response = client.patch(
        f"/api/v1/parts/{part_id}/features/{e_id}",
        json={"expected_tree_version": 3, "feature": _extrude_envelope(s2)},
        headers=_headers(),
    )
    assert response.status_code == 200, response.text

    # Sketch1 is now deletable (no dependents); Sketch2 is not.
    response = client.delete(
        f"/api/v1/parts/{part_id}/features/{s2}",
        params={"expected_tree_version": 4},
        headers=_headers(),
    )
    assert response.status_code == 409
    response = client.delete(
        f"/api/v1/parts/{part_id}/features/{s1}",
        params={"expected_tree_version": 4},
        headers=_headers(),
    )
    assert response.status_code == 200, response.text


def test_update_cannot_change_feature_type(client: TestClient) -> None:
    part_id = _create_part(client)
    sketch_id, _ = _sketch_and_extrude(client, part_id)
    response = client.patch(
        f"/api/v1/parts/{part_id}/features/{sketch_id}",
        json={"expected_tree_version": 2, "feature": _extrude_envelope(sketch_id)},
        headers=_headers(),
    )
    assert response.status_code == 422
    assert _envelope_error(response.json())["code"] == "feature_type_immutable"


# --- upcast-on-read (§1.4) -------------------------------------------------------


@pytest.fixture
def extrude_v0_upcast() -> Iterator[None]:
    """Register a synthetic extrude v0→v1 upcast on the module registry —
    exactly the design's example: v1 made ``direction`` explicit, so the
    upcast fills the ``"normal"`` that v0 semantics implied."""

    def upcast(params: dict[str, Any]) -> dict[str, Any]:
        return {**params, "direction": "normal"}

    FEATURE_REGISTRY.register_upcast("extrude", 0, upcast)
    FEATURE_REGISTRY.validate_chains()
    try:
        yield
    finally:
        # Test-scoped registration only; the module registry is process-global.
        FEATURE_REGISTRY._upcasts.pop(("extrude", 0))  # pyright: ignore[reportPrivateUsage]


async def _insert_raw_feature(
    url: str,
    part_id: str,
    *,
    order_index: int,
    type_: str,
    param_version: int,
    params: dict[str, Any],
) -> None:
    engine = direct_engine(url)
    try:
        async with engine.begin() as connection:
            await connection.execute(
                sa.insert(Feature).values(
                    id=uuid.uuid4(),
                    part_id=uuid.UUID(part_id),
                    order_index=order_index,
                    name="Legacy",
                    type=type_,
                    param_version=param_version,
                    params=params,
                )
            )
    finally:
        await engine.dispose()


def test_old_param_version_is_upcast_on_read(
    client: TestClient, any_db_url: str, extrude_v0_upcast: None
) -> None:
    part_id = _create_part(client)
    sketch = _create_feature(client, part_id, "Sketch1", _sketch_envelope(), 0)
    v0_params = {
        "profile": {"kind": "feature", "feature_id": sketch["feature"]["id"]},
        "distance_mm": 10.0,
        "operation": "add",
        # no "direction" — the field v1 introduced.
    }
    asyncio.run(
        _insert_raw_feature(
            any_db_url,
            part_id,
            order_index=1,
            type_="extrude",
            param_version=0,
            params=v0_params,
        )
    )

    tree = _tree(client, part_id)
    legacy = tree["features"][1]
    # The rest of the system only ever sees current-version params (§1.4).
    assert legacy["feature"]["version"] == 1
    assert legacy["feature"]["params"]["direction"] == "normal"


def test_unloadable_param_version_fails_loudly(
    any_db_url: str,
) -> None:
    """Totality enforcement at the read boundary: a stored version with no
    upcast path is a server-side integrity failure — an opaque 500, never a
    silently-guessed row."""
    settings = DocumentsSettings(postgres_url=any_db_url)
    with TestClient(
        build_app(settings), raise_server_exceptions=False
    ) as no_raise_client:
        part_id = _create_part(no_raise_client)
        asyncio.run(
            _insert_raw_feature(
                any_db_url,
                part_id,
                order_index=0,
                type_="extrude",
                param_version=99,
                params={},
            )
        )
        response = no_raise_client.get(
            f"/api/v1/parts/{part_id}/features", headers=_headers()
        )
    assert response.status_code == 500
    assert _envelope_error(response.json())["code"] == "internal_error"


# --- import base feature (docs/design/step-import.md) ---------------------------


def test_import_creates_base_feature_with_inline_step(client: TestClient) -> None:
    """An import onto an empty part persists the STEP text verbatim as params."""
    part_id = _create_part(client)
    created = _create_feature(client, part_id, "Import1", _import_envelope(), 0)
    assert created["feature"]["feature"] == _import_envelope()
    assert created["tree_version"] == 1
    # Import carries no references, so it materializes no dependency edges.
    tree = _tree(client, part_id)
    [feature] = tree["features"]
    assert feature["feature"]["params"]["data"] == STEP_TEXT


def test_import_allowed_after_non_body_features(client: TestClient) -> None:
    """A datum/sketch before an import is fine — neither produces a body."""
    part_id = _create_part(client)
    _create_feature(client, part_id, "Datum1", _datum_envelope(), 0)
    _create_feature(client, part_id, "Sketch1", _sketch_envelope(), 1)
    response = client.post(
        f"/api/v1/parts/{part_id}/features",
        json={
            "name": "Import1",
            "feature": _import_envelope(),
            "expected_tree_version": 2,
        },
        headers=_headers(),
    )
    assert response.status_code == 201, response.text


def test_import_with_prior_body_rejected(client: TestClient) -> None:
    """An import cannot follow a body-producing feature (step-import.md §1)."""
    part_id = _create_part(client)
    _, extrude_id = _sketch_and_extrude(client, part_id)
    response = client.post(
        f"/api/v1/parts/{part_id}/features",
        json={
            "name": "Import1",
            "feature": _import_envelope(),
            "expected_tree_version": 2,
        },
        headers=_headers(),
    )
    assert response.status_code == 422
    error = _envelope_error(response.json())
    assert error["code"] == "import_with_prior_body"
    assert error["details"]["prior_feature_id"] == extrude_id
    assert error["details"]["prior_feature_type"] == "extrude"


def test_second_import_rejected_as_prior_body(client: TestClient) -> None:
    """A second import also trips the guard — import IS body-affecting."""
    part_id = _create_part(client)
    _create_feature(client, part_id, "Import1", _import_envelope(), 0)
    response = client.post(
        f"/api/v1/parts/{part_id}/features",
        json={
            "name": "Import2",
            "feature": _import_envelope("ISO-10303-21;\nEND-ISO-10303-21;\n"),
            "expected_tree_version": 1,
        },
        headers=_headers(),
    )
    assert response.status_code == 422
    assert _envelope_error(response.json())["code"] == "import_with_prior_body"


# --- scoping --------------------------------------------------------------------


def test_feature_routes_are_owner_scoped(client: TestClient) -> None:
    part_id = _create_part(client)
    _sketch_and_extrude(client, part_id)
    # Foreign part id answers exactly like a nonexistent one.
    foreign = client.get(f"/api/v1/parts/{part_id}/features", headers=_headers(OTHER))
    unknown = client.get(
        f"/api/v1/parts/{uuid.uuid4()}/features", headers=_headers(OTHER)
    )
    assert foreign.status_code == unknown.status_code == 404
    assert _envelope_error(foreign.json())["code"] == "part_not_found"


def test_get_single_feature(client: TestClient) -> None:
    part_id = _create_part(client)
    sketch_id, _ = _sketch_and_extrude(client, part_id)
    response = client.get(
        f"/api/v1/parts/{part_id}/features/{sketch_id}", headers=_headers()
    )
    assert response.status_code == 200
    assert response.json()["feature"] == _sketch_envelope()

    missing = client.get(
        f"/api/v1/parts/{part_id}/features/{uuid.uuid4()}", headers=_headers()
    )
    assert missing.status_code == 404
    assert _envelope_error(missing.json())["code"] == "feature_not_found"


def test_missing_principal_401(client: TestClient) -> None:
    response = client.get(f"/api/v1/parts/{uuid.uuid4()}/features")
    assert response.status_code == 401
    assert _envelope_error(response.json())["code"] == "missing_principal"
